#version 450
#extension GL_EXT_shader_explicit_arithmetic_types         : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int8    : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16   : require
#extension GL_EXT_shader_explicit_arithmetic_types_int32   : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64   : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_float32 : require
#extension GL_EXT_shader_explicit_arithmetic_types_float64 : require
#extension GL_EXT_debug_printf : enable

layout (binding=0, rgba32f) uniform image2D positionOutput;
layout (binding=1, rgba8) uniform image2D albedoOutput;
layout (binding=2, rgba8) uniform image2D normalOutput;

void main() {
    imageStore(positionOutput, ivec2(gl_GlobalInvocationID.xy), vec4(0.0));
    imageStore(albedoOutput, ivec2(gl_GlobalInvocationID.xy), vec4(0.0));
    imageStore(normalOutput, ivec2(gl_GlobalInvocationID.xy), vec4(0.0));
}
